config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: :show
    resources :categories,          only: :show
    resources :suggests,            only: :index
    namespace :api do
      get :suggests, to: 'suggests#suggests_response'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potepan.rb
module Potepan
  def self.table_name_prefix
    'potepan_'
  end
end

app/models/potepan/suggest.rb
class Potepan::Suggest < ApplicationRecord
end

app/models/spree/product_decorator.rb
module Spree::ProductDecorator
  Spree::Product.include self
  RELATED_PRODUCT_MAX_DISPLAY_NUMBER = 4

  # @productと関連性が高い（taxonsでの繋がりが多い）商品を先頭にソートした関連商品を返す
  def related_products
    Spree::Product.includes(master: [:default_price, :images]).
      in_taxons(taxons).
      where.not(id: id).
      group_by { |product| product }.
      sort_by { |key, value| -value.size }.
      take(RELATED_PRODUCT_MAX_DISPLAY_NUMBER).
      map(&:first)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/api/suggests_controller.rb
class Potepan::Api::SuggestsController < ApplicationController
  include ActionController::HttpAuthentication::Token::ControllerMethods
  WORD_COUNT_SUGGESTED_IN_DEFAULT = 3
  before_action :authenticate

  def suggests_response
    raise unless params[:keyword]
    render json: suggest_words
  end

  private

  def authenticate
    authenticate_or_request_with_http_token do |token|
      ActiveSupport::SecurityUtils.secure_compare(token, ENV['TASK5_2_WEBAPI_KEY'])
    end
  end

  def suggest_words
    acquisition_count = params[:max_num] =~ /\A[1-9][0-9]*\z/ ? params[:max_num] : WORD_COUNT_SUGGESTED_IN_DEFAULT
    Potepan::Suggest.where("keyword LIKE(?)", "#{params[:keyword]}%").limit(acquisition_count).pluck("keyword")
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxonomies = Spree::Taxonomy.includes(:taxons)
    @taxon = Spree::Taxon.find(params[:id])
    @products = @taxon.all_products.includes(master: [:default_price, :images])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def show
    @product = Spree::Product.find(params[:id])
    @ralated_products = @product.related_products
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/suggests_controller.rb
class Potepan::SuggestsController < ApplicationController
  def index
    connection = Faraday.new(ENV['POTEPAN_WEBAPI_HOST'])
    response =
      connection.get ENV['POTEPAN_WEBAPI_PATH'] do |request|
        request.headers['Authorization'] = "Bearer #{ENV['POTEPAN_WEBAPI_KEY']}"
        request.params[:keyword] = params[:keyword]
        request.params[:max_num] = 5
      end
    response.status == Rack::Utils::SYMBOL_TO_STATUS_CODE[:ok] ? (render json: response.body) : (head response.status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title: "")
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def display_taxon?(taxon)
    taxon.products.count.nonzero?
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def list_page(product)
    if request.referrer && Rails.application.routes.recognize_path(request.referrer)[:controller] == "potepan/categories"
      request.referrer
    else
      potepan_category_path(product.taxons.first&.id || 1)
    end
  end
end

app/views/layouts/_footer.html.slim
/ FOOTER
/ COPY RIGHT
#footer.copyRight.clearfix
  .container
    .row
      .col-sm-7.col-xs-12
        p
          | &copy; 2016-
          = Time.zone.now.year
          |  Copyright Potepan Store
      .col-sm-5.col-xs-12
        ul.list-inline
          li
            a href="#"
              i.fa.fa-twitter
          li
            a href="#"
              i.fa.fa-facebook

app/views/layouts/_head.html.slim
/ HEAD
= csrf_meta_tags
meta charset="utf-8"
meta http-equiv="X-UA-Compatible" content="IE=EDGE"
meta name="viewport" content="width=device-width, initial-scale=1"
/ SITE TITLE
title = full_title(page_title: yield(:title))
/ GOOGLE FONT
= stylesheet_link_tag("application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', media: "all")
= render "layouts/shim"

app/views/layouts/_header.html.slim
/ HEADER
.header.clearfix
  / TOPBAR
  .topBar
    .container
      .row
        .col-md-6.hidden-sm.hidden-xs
          ul.list-inline
            li
              a href="#"
                i.fa.fa-twitter
            li
              a href="#"
                i.fa.fa-facebook
        .col-md-6.col-xs-12
          ul.list-inline.pull-right
            li
            li.dropdown.searchBox.active
              a#searchBox.dropdown-toggle data-toggle="dropdown" href="javascript:void(0)"
                i.fa.fa-search
              ul.dropdown-menu.dropdown-menu-right
                form#form01 action="product-grid-left-sidebar.html" method="post"
                  li
                    span.input-group
                      input.form-control aria-describedby="basic-addon2" name="searchWord" placeholder="Search…" type="text" autocomplete="off"
                      span#basic-addon2.input-group-addon.addPointer onclick="FormSubmit();" 検索
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown disabled" href="cart-page.html"
                i.fa.fa-shopping-cart
  / NAVBAR
  nav.navbar.navbar-main.navbar-default role="navigation"
    .container
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        button.navbar-toggle data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        .navbar-brand = link_to image_tag("img/logo.png", alt: "BIGBAG"), potepan_path
      / Collect the nav links, forms, and other content for toggling
      .collapse.navbar-collapse.navbar-ex1-collapse
        ul.nav.navbar-nav.navbar-right
          li.active
            = link_to "Home", potepan_path
          li.dropdown.megaDropMenu
            a.dropdown-toggle aria-expanded="false" data-close-others="true" data-delay="300" data-hover="dropdown" data-toggle="dropdown" href="javascript:void(0)" Shop

app/views/layouts/_login_modal.html.slim
/ LOGIN MODAL
#login.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-hidden="true"
          | &times;
        h3.modal-title log in
      .modal-body
        form action="" method="POST" role="form"
          .form-group
            label for="login-email" Enter Email
            input#login-email.form-control
          .form-group
            label for="login-password" Password
            input#login-password.form-control
          .checkbox
            label
              input type="checkbox" Remember Me
          button.btn.btn-primary.btn-block type="submit" log in
          button.btn.btn.link.btn-block type="button" Forgot Password?

app/views/layouts/_shim.html.slim
/ HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
/ WARNING: Respond.js doesn't work if you view the page via file://
/[if lt IE 9]
  script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"
  script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

app/views/layouts/_signup_modal.html.slim
/ SIGN UP MODAL
#signup.modal.fade tabindex="-1" role="dialog"
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-hidden="true"
          | &times;
        h3.modal-title Create an account
      .modal-body
        form action="" method="POST" role="form"
          .form-group
            label for="signpu-email" Enter Email
            input#signup-email.form-control type="email"
          .form-group
            label for="sign-up-password" Password
            input#signup-password.form-control type="password"
          .form-group
            label form="signup-password-confirmation" Confirm Password
            input#signup-password-confirmation.form-control
          button.btn.btn-primary.btn-block type="submit" Sign up

app/views/layouts/application.html.slim
doctype html
html
  head
    = render "layouts/head"
  body
    .main-wrapper
      = render "layouts/header"
      = yield
      = render "layouts/footer"
    = render "layouts/login_modal"
    = render "layouts/signup_modal"
    = javascript_include_tag "application"

app/views/potepan/_partners_logo_slider.html.slim
/ LIGHT SECTION
section.lightSection.clearfix
  .container
    .row
      .col-xs-12
        .owl-carousel.partnersLogoSlider
          .slide
            .partnersLogo.clearix
              = image_tag("img/home/partners/partner-01.png", alt: "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-02.png", alt: "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-03.png", alt: "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-04.png", alt: "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-05.png", alt: "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-01.png", alt: "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-02.png", alt: "partner-img")
          .slide
            .partnersLogo.clearfix
              = image_tag("img/home/partners/partner-03.png", alt: "partner-img")

app/views/potepan/categories/_light_section.html.slim
/ LIGHT SECTION
section.lightSection.clearfix.pageHeader
  .container
    .row
      .col-xs-6
        .page-title
          h2 = taxon.name
      .col-xs-6
        ol.breadcrumb.pull-right
          li
            = link_to "Home", potepan_path
          li
            = link_to "Shop", "#"
          li.active
            = taxon.name

app/views/potepan/categories/_main_content_section.html.slim
/ MAIN CONTENT SECTON
section.mainContent.clearfix.productsContent
  .container
    .row
      .col-md-3.conl-sm-4.col-xs-12.sideBar
        = render  "potepan/categories/product_category_panel", taxonomies: taxonomies
        .panel.panel-default.filterNormal
          .panel-heading
            | 色から探す
          .panel-body
            ul.list-unstyled
              li
                a href="#"
                  | ブラック
                  span
                    | (15)
              li
                a href="#"
                  | ホワイト
                  span
                    | (10)
              li
                a href="#"
                  | レッド
                  span
                    | (7)
              li
                a href="#"
                  | ブルー
                  span
                    | (12)
              li
                a href="#"
                  | オレンジ
                  span
                    | (12)
        .panel.panel-default.filterNormal
          .panel-heading
            | サイズから探す
          .panel-body
            ul.list-unstyled.clearfix
              li
                a href="#"
                  | S
                  span
                    | (15)
              li
                a href="#"
                  | M
                  span
                    | (10)
              li
                a href="#"
                  | L
                  span
                    | (7)
              li
                a href="#"
                  | XL
                  span
                    | (12)
      .col-md-9.col-sm-8.col-xs-12
        .row.filterArea
          .col-xs-6
            select#guiest_id1.select-drop name="guiest_id1"
              option value="0"
                | 並び替え
              option value="1"
                | 人気順
              option value="2"
                | 安い順
              option value="3"
                | 新着順
              option value="4"
                | 高い順
          .col-xs-6
            .btn-group.pull-right role="group"
              button.btn.btn-default.active type="button" onclick="window.location.href='product_grid_left_sidebar.html'"
                i.fa.fa-th aria-hidden="true"
                span
                  | Grid
              button.btn.btn-default type="button" onclick="window.location.href='product_list_left_sidebar.html'"
                i.fa.fa-th-list aria-hidden="true"
                span
                  | List
        .row
          = render partial: "product", collection: products

app/views/potepan/categories/_product.html.slim
.col-sm-4.col-xs-12
  = link_to potepan_product_path(product.id)
    .productBox
      .productImage.clearfix
        = image_tag(product.display_image.attachment(:product), alt: product.name)
      .productCaption.clearfix
        h5 = product.name
        h3 = product.display_price

app/views/potepan/categories/_product_category_panel.html.slim
.panel.panel-default
  .panel-heading
    | 商品カテゴリー
  .panel-body
    .collapse.navbar-collapse.navbar-ex1-collapse.navbar-side-collapse
      ul.nav.navbar-nav.side-nav
        - taxonomies.each do |taxonomy|
          li
            a href="javascript:;" data-toggle="collapse" data-target="##{taxonomy.name}"
              = taxonomy.name
              i.fa.fa-plus
            ul id=taxonomy.name class="collapse collapseItem"
              - taxonomy.taxons.each do |taxon|
                - if display_taxon?(taxon)
                  li
                    a href="#{taxon.id}"
                      i.fa.fa-caret-right aria-hidden="true"
                      = taxon.name
                      span
                      = "(#{taxon.all_products.count})"

app/views/potepan/categories/show.html.slim
= provide(:title, @taxon.name)
= render "light_section", taxon: @taxon
= render "main_content_section", taxonomies: @taxonomies, products: @products
= render "potepan/partners_logo_slider"

app/views/potepan/products/_light_section.html.slim
/ LIGHT SECTION
section.lightSection.clearfix.pageHeader
  .container
    .row
      .col-xs-6
        .page-title
          h2 = product.name
      .col-xs-6
        ol.breadcrumb.pull-right
          li
            = link_to "Home", potepan_path
          li.active
            = product.name

app/views/potepan/products/_main_content_section.html.slim
/ MAIN CONTENT
section.mainContent.clearfix
  .container
    .row.singleProduct
      .col-xs-12
        .media
          .media-left.productSlider
            #carousel.carousel.slide data-ride="carousel"
              .carousel-inner
                - product.master_images.each_with_index do |image, index|
                  .item class=(index.zero? ? "active" : "") data-thumb="#{index}"
                    = image_tag image.attachment(:large)
            .clearfix
              #thumbcarousel.carousel.slide data-interval="false"
                .carousel-inner
                  - product.master_images.each_with_index do |image, index|
                    .thumb data-target="#carousel" data-slide-to="#{index}"
                      = image_tag image.attachment(:small)
                a.left.carousel-control href="#thumbcarousel" role="button" data-slide="prev"
                  span.glyphicon.glyphicon-chevron-left
                a.right.carousel-control href="#thumbcarousel" role="button" data-slide="next"
                  span.glyphicon.glyphicon-chevron-right
          .media-body
            ul.list-inline
              li
                = link_to list_page(product)
                  i.fa.fa-reply aria-hidden="true"
                  | 一覧ページへ戻る
            h2 = product.name
            h3 = product.display_price
            p = product.description
            span.quick-drop
              select#guiest_id3.select-drop name="guiest_id3"
                option value="0" S
                option value="1" M
                option value="2" L
                option value="3" XL
            span.quick-drop.resizeWidth
              select#guiest_id4.select-drop name="guiest_id4"
                option value="1" 1
                option value="2" 2
                option value="3" 3
            .btn-area
              a.btn.btn-primary.btn-block href="cart_page.html"
                | カートへ入れる
                i.fa.fa-angle-right aria-hidden="true"
    .row.productsContent
      .col-xs-12
        .page-header
          h4 関連商品
      = render partial: "related_product", collection: ralated_products

app/views/potepan/products/_related_product.html.slim
.col-md-3.col-sm-6.col-xs-12
  = link_to potepan_product_path(related_product.id)
    .productBox
      .productImage.clearfix
        = image_tag(related_product.display_image.attachment(:product), alt: related_product.name)
      .productCaption.clearfix
        h5 = related_product.name
        h3 = related_product.display_price

app/views/potepan/products/show.html.slim
- provide(:title, @product.name)
= render "light_section", product: @product
= render "main_content_section", product: @product, ralated_products: @ralated_products

app/views/potepan/sample/checkout_complete.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Order Completed - BIGBAG Store</title>

    <!-- PLUGINS CSS STYLE -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

    <!-- CUSTOM CSS -->
    <link href="css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="css/colors/default.css" id="option_color">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="main-wrapper">

      <!-- HEADER -->
      <div class="header clearfix">

        <!-- TOPBAR -->
        <div class="topBar">
          <div class="container">
            <div class="row">
              <div class="col-md-6 hidden-sm hidden-xs">
                <ul class="list-inline">
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                </ul>
              </div>
              <div class="col-md-6 col-xs-12">
                <ul class="list-inline pull-right">
                  <li><!-- <span><a data-toggle="modal" href='.login-modal'>ログイン</a><small>or</small><a data-toggle="modal" href='#signup'>新規登録</a></span> --></li>
                  <li class="dropdown searchBox">
                    <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
                    <ul class="dropdown-menu dropdown-menu-right">
                      <form  id="form01" action="product-grid-left-sidebar.html" method="post">
                      <li>
                        <span class="input-group">
                          <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                          <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                        </span>
                      </li>
                      </form>
                    </ul>
                  </li>
                  <li class="dropdown">
                    <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- NAVBAR -->
        <nav class="navbar navbar-main navbar-default" role="navigation">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html"><%= image_tag("logo.png") %></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li class=""><a href="index.html">Home</a></li>
                <li class="dropdown megaDropMenu">
                  <a href="product-grid-left-sidebar.html" class="dropdown-toggle">Shop</b></a>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div>
        </nav>

      </div>

      <!-- LIGHT SECTION -->
      <section class="lightSection clearfix pageHeader">
        <div class="container">
          <div class="row">
            <div class="col-xs-6">
              <div class="page-title">
                <h2>thanks message</h2>
              </div>
            </div>
            <div class="col-xs-6">
              <ol class="breadcrumb pull-right">
                <li>
                  <a href="index.html">Home</a>
                </li>
                <li class="active">thanks message</li>
              </ol>
            </div>
          </div>
        </div>
      </section>

      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix setp5">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="thanksContent">
                <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
                <h3>Shipping Details</h3>
                <div class="thanksInner">
                  <div class="row">
                    <div class="col-sm-6 col-xs-12 tableBlcok">
                      <address>
                        <span>Shipping address:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                        <span>Email:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                        <span>Phone:</span> +884 5452 6432
                      </address>
                    </div>
                    <div class="col-sm-6 col-xs-12">
                      <div class="well">
                        <h2><small>Order ID</small>9547</h2>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- FOOTER -->
      <!-- COPY RIGHT -->
      <div id="footer" class="copyRight clearfix">
        <div class="container">
          <div class="row">
            <div class="col-sm-7 col-xs-12">
              <p>&copy; 2016-<%= Time.now.year %> Copyright Potepan Store .</p>
            </div>
            <div class="col-sm-5 col-xs-12">
              <ul class="list-inline">
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- LOGIN MODAL -->
    <div class="modal fade" id="login" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">log in</h3>
          </div>
          <div class="modal-body">
            <form action="" method="POST" role="form">
              <div class="form-group">
                <label for="login-email">Enter Email</label>
                <input type="email" class="form-control" id="login-email">
              </div>
              <div class="form-group">
                <label for="login-password">Password</label>
                <input type="password" class="form-control" id="login-password">
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Remember Me
                </label>
              </div>
              <button type="submit" class="btn btn-primary btn-block">log in</button>
              <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- SIGN UP MODAL -->
    <div class="modal fade" id="signup" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">Create an account</h3>
          </div>
          <div class="modal-body">
            <form action="" method="POST" role="form">
              <div class="form-group">
                <label for="signup-email">Enter Email</label>
                <input type="email" class="form-control" id="signup-email">
              </div>
              <div class="form-group">
                <label for="signup-password">Password</label>
                <input type="password" class="form-control" id="signup-password">
              </div>
              <div class="form-group">
                <label for="signup-password-confirmation">Confirm Password</label>
                <input type="password" class="form-control" id="signup-password-confirmation">
              </div>
              <button type="submit" class="btn btn-primary btn-block">Sign up</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>